CREATE TABLE TODOITEM (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    completed BIT NOT NULL
);

CREATE INDEX idx_username ON TODOITEM(username);

CREATE SEQUENCE IF NOT EXISTS SEQ_ID START WITH 1 INCREMENT BY 1;